### ISSUE TITLE
Server side memory usage

### ISSUE THREAD

**Issue by 7Grok** [priologic/easyrtc#275] opened 2016-10-19 15:22 UTC
We have EasyRTC 1.0.15 running on node 4.4.7. We typically have around 60 - 100 users connected for at least 8+ hours each day. Each sessions lasts about 5-10 minutes. We restart the system each morning at 4AM EST. We have noticed that our memory usage grows significantly throughout the day. Right now 11AM EST the node process is using 2.1GB of RAM and we have --max-old-space-size=5120 because we used to run out of RAM around 2-3PM EST.

Do you have any advice on things we should be doing or not doing when we have many connects and disconnects from the server ? Anything we should check for memory bloat or any other advice in general?

We are not sure were to go from here other than keep throwing more RAM at it.

**Comment by hthetiot** [comment] 2016-10-19 18:21
I never had that kind of issues.
Did you added or changed the server listener logic or you just running plain example server ?

**Comment by hthetiot** [comment] 2016-10-19 18:23
Next release will have an update on socket.io to 1.4.5 try the beta branch or wait for release in coming days if you want to see if it has an impact.

**Comment by 7Grok** [comment] 2016-10-19 19:49
Nope we are running the sample server. We have not modified the code the RTC code. It is running inside another node app that we have, but thats so it can gain access to authentication data for each user to the best of my knowledge this app was well behaved before EasyRTC. Right now at 3:47 EST its using 4.57GB of RAM

**Comment by EricDavies** [comment] 2016-10-19 20:41
First thought: have you tried triggering garbage collection explicitly, just to see what affect it has. This page indicates how to measure memory consumption and how to trigger garbage collection:
http://stackoverflow.com/questions/27321997/how-to-request-the-garbage-collector-in-node-js-to-run

Second thought: the first step in tracking down something like this is knowing how to generate the problem. Can you produce a script that connects to a vanilla easyrtc server, duplicates your typical interaction and hence reproduces the problem?

This is something that should be in our google groups rather than github, given its a question/problem rather than a report of a well defined bug or a feature request. 
 https://groups.google.com/forum/?fromgroups#!forum/easyrtc

**Comment by hthetiot** [comment] 2016-10-20 18:49
@7Grok if you run some other JavaScript at the same time we cannot be sure it is related to EasyRTC.

What I would do, is run the pure server example in parallel of you app and use it for the signaling to see if the problem is in your app over easyRTC server signaling.

I'm closing for now. Re-open if you can reproduce with pure sample.

**Closed by hthetiot** 2016-10-20 18:49 UTC
Labels: question, server

**Comment by 7Grok** [comment] 2016-11-16 21:33
For anyone that finds this. I think we managed to fix the issue. See this for more info. https://groups.google.com/forum/#!topic/easyrtc/oGxXJ0irmds
