### ISSUE TITLE
Shows "Not yet connected..." even though the connection is made

### ISSUE THREAD

**Issue by neeraj87** [priologic/easyrtc#411] opened 2018-09-21 15:48 UTC
I am replicating the [Simple Video + Audio](https://demo.easyrtc.com/demos/demo_audio_video_simple.html) sample on my application. When I open the chat page I can see myself in the webcam but it still shows "Not yet connected...". 

Worst, I can't even see other users who are connected to my chat page. 
When I debug I do not see any errors. 

I have Node.js application but my html page is public.

<img width="1550" alt="screen shot 2018-09-21 at 9 21 02 pm" src="https://user-images.githubusercontent.com/7267014/45892000-93859b00-bde4-11e8-975a-5882074a688e.png">

**Comment by hthetiot** [comment] 2018-09-24 17:20
@neeraj87 does the demo code work locally for you?
Did you connect, then join room ?

Here is master demo running for reference:
- https://easyrtc.sylaps.net

**Comment by neeraj87** [comment] 2018-09-25 04:53
No, the code is not working locally as well. I can only see myself (the green screen block).

<img width="1680" alt="screen shot 2018-09-25 at 10 21 10 am" src="https://user-images.githubusercontent.com/7267014/45993497-e98c6400-c0ac-11e8-8e92-ac713321e7bb.png">

**Comment by neeraj87** [comment] 2018-09-30 16:51
Any updates on this issue?

**Comment by hthetiot** [comment] 2018-09-30 20:11
I cannot reproduce sorry, the demo code and demo instance work for me.

Can you try again here:
- https://easyrtc.sylaps.net/demos/demo_audio_video.html

Make sure you use master, I merged beta few days ago. It look to me the page you have taken a screenshot has errors or you have certificate issues on websocket that can be an explaination.

**Comment by hthetiot** [comment] 2018-09-30 20:12
Check this in case of https://github.com/priologic/easyrtc/issues/410

**Comment by hthetiot** [comment] 2018-09-30 20:14
Make server example work locally first. 
- 
https://github.com/priologic/easyrtc/blob/master/docs/easyrtc_server_install.md#git-install-steps

**Comment by hthetiot** [comment] 2018-09-30 20:15
Reopen if you find an issue and fail to make it works locally.

**Closed by hthetiot** 2018-09-30 20:15 UTC
Labels: help, question
