### ISSUE TITLE
Mediastream methods being deprecated by Chrome

### ISSUE THREAD

**Issue by bbeans** [priologic/easyrtc#163] opened 2015-10-13 18:56 UTC
Using EasyRTC v1.0.14:

'MediaStream.stop()' is deprecated and will be removed in M47, around November 2015. Please use 'MediaStream.active' instead.

easyrtc.js:3192 'MediaStream.ended' is deprecated and will be removed in M47, around November 2015. Please use 'MediaStream.active' instead.

**Comment by EricDavies** [comment] 2015-10-14 04:43
Fixed in the beta branch.

**Closed by EricDavies** 2015-10-14 04:43 UTC

**Comment by hthetiot** [comment] 2015-10-14 07:31
@EricDavies I also had to fix some bug since Chrome M47 where MediaStream.hasOwnProperty("id") return false now, also noticed that before on Firefox.

It may can be also caused by easyrtc creating or changing the property on the object making hasOwnProperty return false has expected.
I did not experimented the issue using the default stream but named multistream only and not auto iniMedia.

Here is the quick patch for reference.
https://github.com/hthetiot/easyrtc/commit/d7022955d216e1ce6c019742fedc00591caf7398

**Comment by EricDavies** [comment] 2015-10-14 15:01
In the version I pushed, I used an index instead of a foreach type loop, so
its already taken care of.

**Comment by hthetiot** [comment] 2015-10-14 16:31
@EricDavies there is still hasOwnProperty that fail on priologic beta
branch for me.

if (stream.hasOwnProperty("id")) {
            id = stream.id;
        }


On Wednesday, October 14, 2015, Eric Davies <notifications@github.com>
wrote:

> In the version I pushed, I used an index instead of a foreach type loop, so
> its already taken care of.
>
> On Wed, Oct 14, 2015 at 12:31 AM, Harold Thétiot <notifications@github.com
> <javascript:_e(%7B%7D,'cvml','notifications@github.com');>>
> wrote:
>
> > @EricDavies <https://github.com/EricDavies> I also had to fix some bug
> > since Chrome M47 where MediaStream.hasOwnProperty("id") return false now,
> > also noticed that before on Firefox.
> >
> > It may can be also caused by easyrtc creating or changing the property on
> > the object making hasOwnProperty return false has expected.
> > I did not experimented the issue using the default stream but named
> > multistream only and not auto iniMedia.
> >
> > Here is the quick patch for reference.
> > hthetiot@d702295
> > <
> https://github.com/hthetiot/easyrtc/commit/d7022955d216e1ce6c019742fedc00591caf7398
> >
> >
> > —
> > Reply to this email directly or view it on GitHub
> > <https://github.com/priologic/easyrtc/issues/163#issuecomment-147962215
> >.
> >
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/priologic/easyrtc/issues/163#issuecomment-148077337>.
>


-- 
Harold Thétiot.

**Comment by hthetiot** [comment] 2015-10-14 16:32
Try multi stream named on chrome you will see receiver fail to get stream
cause of fail hasOwn on is that I fixed on my branch.

On Wednesday, October 14, 2015, Eric Davies <notifications@github.com>
wrote:

> In the version I pushed, I used an index instead of a foreach type loop, so
> its already taken care of.
>
> On Wed, Oct 14, 2015 at 12:31 AM, Harold Thétiot <notifications@github.com
> <javascript:_e(%7B%7D,'cvml','notifications@github.com');>>
> wrote:
>
> > @EricDavies <https://github.com/EricDavies> I also had to fix some bug
> > since Chrome M47 where MediaStream.hasOwnProperty("id") return false now,
> > also noticed that before on Firefox.
> >
> > It may can be also caused by easyrtc creating or changing the property on
> > the object making hasOwnProperty return false has expected.
> > I did not experimented the issue using the default stream but named
> > multistream only and not auto iniMedia.
> >
> > Here is the quick patch for reference.
> > hthetiot@d702295
> > <
> https://github.com/hthetiot/easyrtc/commit/d7022955d216e1ce6c019742fedc00591caf7398
> >
> >
> > —
> > Reply to this email directly or view it on GitHub
> > <https://github.com/priologic/easyrtc/issues/163#issuecomment-147962215
> >.
> >
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/priologic/easyrtc/issues/163#issuecomment-148077337>.
>


-- 
Harold Thétiot.
